apiVersion: v1
kind: PersistentVolume
metadata:
  name: iovns
spec:
  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/iovns
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: iovns
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Mi